runtime: php55
api_version: 1

handlers:
- url: /template/images
  static_dir: template/images
- url: /template/css
  static_dir: template/css
- url: /template/js
  static_dir: template/js
- url: /template/fonts
  static_dir: template/fonts
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: index.php